### PR TITLE
Clang format target change

### PR DESCRIPTION
**Pull request by 0-EricZhou-0**
Clang format is changed to only execute on git tracked files

### CODE REVIEW

**Comment by AzulRadio** [comment]
After this change, we will need an extra commit for check-format on every branch which might pollute the history. Besides, I don't see any big advantage in doing so. Could you justify the advantage?

**Comment by 0-EricZhou-0** [comment]
> After this change, we will need an extra commit for check-format on every branch which might pollute the history. Besides, I don't see any big advantage in doing so. Could you justify the advantage?

What do you mean by "an extra commit on every branch", could you elaborate on that?

I propose this to address the problem that generated files may violate the `clang-format` specifications, and the original version would check format against those generated files locally, which in turn generate false alarms.

**Comment by AzulRadio** [comment]
Say we create a new source file, I cannot format-check it until I add it to a commit. 

>generated files may violate

No they just won't because the generated header is so simple. Even if that is a concern we should consider using `list(FILTER EXCLUDE` to ignore the folder instead of making Cmake depending on git. It just doesn't feel right.

**Comment by 0-EricZhou-0** [comment]
That makes sense.

We can also do a `list(FILTER EXCLUDE)` instead, but how are we going to differentiate which file is generated and which one is not?

I did this because I `check-format` complained about the generated files because they have an extra line at the end of the file. Although we can change it when generating those files, I prefer to exclude them because no one would really read those files.

**Comment by AzulRadio** [comment]
Thus far all the generated files ended with _CONFIG.h. We will put it in a designated folder in the future (exclude the folder then). You can also edit the generator script to get rid of the extra line.

**Comment by 0-EricZhou-0** [comment]
OK, I will close this pr then.

**Pull request closed without merging**
